import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import MouseCursor from "./components/mouseCursor";
import HeaderLayout from "./components/headerLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
      
  return (
    <html lang="en">
      <HeaderLayout children={children} geistSans={geistSans} geistMono={geistMono}></HeaderLayout>
    </html>
  );
}
