export const classData3a = [
    { id: 1, last_name: "Abrique", first_name: "Regine" },
    { id: 2, last_name: "Aguilar", first_name: "Michael" },
    { id: 3, last_name: "Alamo", first_name: "Adrian" },
    { id: 4, last_name: "Ali", first_name: "Aliester Yussef" },
    { id: 5, last_name: "Andes", first_name: "Lorilette" },
    { id: 6, last_name: "Antonis", first_name: "John Adrian" },
    { id: 7, last_name: "Araña", first_name: "Robert John" },
    { id: 8, last_name: "Arao", first_name: "Shane Marie" },
    { id: 9, last_name: "Arganda", first_name: "Angelica Toni" },
    { id: 10, last_name: "Ariola", first_name: "Chin Danice" },
    { id: 11, last_name: "Azupardo", first_name: "Sonny" },
    { id: 12, last_name: "Balmas", first_name: "Ma. Cindy" },
    { id: 13, last_name: "Buen", first_name: "John Tristan" },
    { id: 14, last_name: "Cellona", first_name: "Dianna Faith" },
    { id: 15, last_name: "Dajac", first_name: "Junieca" },
    { id: 16, last_name: "De Los Angeles", first_name: "Shyla" },
    { id: 17, last_name: "Federnales", first_name: "Joseph Jr" },
    { id: 18, last_name: "Llamera", first_name: "John Carlo" },
    { id: 19, last_name: "Llaneta", first_name: "Kian Vincent" },
    { id: 20, last_name: "Locañas", first_name: "George" },
    { id: 21, last_name: "Loremia", first_name: "Neil Andrei" },
    { id: 22, last_name: "Madraso", first_name: "Jeepy" },
    { id: 23, last_name: "Marcellana", first_name: "Cielo" },
    { id: 24, last_name: "Melecio", first_name: "Jillian Izach" },
    { id: 25, last_name: "Morada", first_name: "Judiel Jose" },
    { id: 26, last_name: "Negrete", first_name: "Jay-R" },
    { id: 27, last_name: "Ortega", first_name: "Nickie Shane" },
    { id: 28, last_name: "Padilla", first_name: "Jay" },
    { id: 29, last_name: "Paladin", first_name: "Jomari" },
    { id: 30, last_name: "Peralta", first_name: "John Raphael" },
    { id: 31, last_name: "Perez", first_name: "Sarah" },
    { id: 32, last_name: "Velarde", first_name: "Gilbert Jr" }
];
