export const classData3b = [
    { id: 1, last_name: "Agravante", first_name: "Prince Elvin" },
    { id: 2, last_name: "Alcazar", first_name: "Princess Jane" },
    { id: 3, last_name: "Atuli", first_name: "John Paul" },
    { id: 4, last_name: "Avellano", first_name: "Rhoda" },
    { id: 5, last_name: "Balla", first_name: "Ramon John Ian" },
    { id: 6, last_name: "Banzuela", first_name: "Marc Jerry" },
    { id: 7, last_name: "Bobiles", first_name: "Ruth" },
    { id: 8, last_name: "Buiza", first_name: "Charles Niño" },
    { id: 9, last_name: "Camu", first_name: "Benjamin Jr" },
    { id: 10, last_name: "Cantero", first_name: "Aimarie" },
    { id: 11, last_name: "Datos", first_name: "Lindralph John" },
    { id: 12, last_name: "Dela Cruz", first_name: "John Dave" },
    { id: 13, last_name: "Dinglasan", first_name: "Janelle" },
    { id: 14, last_name: "Domingo", first_name: "Leonard Alfred" },
    { id: 15, last_name: "Jepsani", first_name: "Shane Anne" },
    { id: 16, last_name: "Lagonoy", first_name: "Kathlene Cate" },
    { id: 17, last_name: "Lopez", first_name: "Zaki" },
    { id: 18, last_name: "Losañez", first_name: "Lorraine Marie" },
    { id: 19, last_name: "Lubidicis", first_name: "Faye" },
    { id: 20, last_name: "Malasa", first_name: "John Denniel" },
    { id: 21, last_name: "Marfil", first_name: "Nicole" },
    { id: 22, last_name: "Marquez", first_name: "Emmanuel" },
    { id: 23, last_name: "Mascariñas", first_name: "Jyro" },
    { id: 24, last_name: "Matociño", first_name: "Kimberly" },
    { id: 25, last_name: "Mazo", first_name: "Ken Ashley" },
    { id: 26, last_name: "Mendoza", first_name: "Jhondel" },
    { id: 27, last_name: "Menguilla", first_name: "Vanexa Beyonce" },
    { id: 28, last_name: "Mirandilla", first_name: "Alexa Kurt" },
    { id: 29, last_name: "Morada", first_name: "Alma" },
    { id: 30, last_name: "Neo", first_name: "Ma. Lenneth Faye" },
    { id: 31, last_name: "Olimpo", first_name: "Marylyn" },
    { id: 32, last_name: "Perez", first_name: "Kim" },
    { id: 33, last_name: "Predilla", first_name: "Jade Angel" },
    { id: 34, last_name: "Prellegera", first_name: "Jerald" },
    { id: 35, last_name: "Risare", first_name: "Dennis Keith" },
    { id: 36, last_name: "Robrigado", first_name: "Jenny" },
    { id: 37, last_name: "Rodriguez", first_name: "Shaina" },
    { id: 38, last_name: "Rodriguez", first_name: "Shine" },
    { id: 39, last_name: "Valenzuela", first_name: "Mark Angel" }
];
